---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    k8s-app: meshnet
  name: meshnet
spec:
  selector:
    matchLabels:
      name: meshnet
  template:
    metadata:
      labels:
        name: meshnet
    spec:
      containers:
        - env:
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: INTER_NODE_LINK_TYPE
              #value: GRPC
              value: VXLAN
          image: meshnet
          imagePullPolicy: IfNotPresent
          name: meshnet
          resources:
            limits:
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 200Mi
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /etc/cni/net.d
              name: cni-cfg
            - mountPath: /opt/cni/bin
              name: cni-bin
            - mountPath: /var/run/netns
              mountPropagation: Bidirectional
              name: var-run-netns
      hostIPC: true
      hostNetwork: true
      hostPID: true
      nodeSelector:
        kubernetes.io/arch: amd64
      serviceAccountName: meshnet
      terminationGracePeriodSeconds: 30
      tolerations:
        - effect: NoSchedule
          operator: Exists
      volumes:
        - hostPath:
            path: /opt/cni/bin
          name: cni-bin
        - hostPath:
            path: /etc/cni/net.d
          name: cni-cfg
        - hostPath:
            path: /var/run/netns
          name: var-run-netns
