---
apiVersion: v1
items:
  - apiVersion: networkop.co.uk/v1beta1
    kind: Topology
    metadata:
      name: r1
    spec:
      links:
        - local_intf: eth1
          local_ip: 12.12.12.1/24
          peer_intf: eth1
          peer_ip: 12.12.12.2/24
          peer_pod: r2
          uid: 1
        - local_intf: eth2
          local_ip: 13.13.13.1/24
          peer_intf: eth1
          peer_ip: 13.13.13.3/24
          peer_pod: r3
          uid: 2
  - apiVersion: networkop.co.uk/v1beta1
    kind: Topology
    metadata:
      name: r2
    spec:
      links:
        - local_intf: eth1
          local_ip: 12.12.12.2/24
          peer_intf: eth1
          peer_ip: 12.12.12.1/24
          peer_pod: r1
          uid: 1
        - local_intf: eth2
          local_ip: 23.23.23.2/24
          peer_intf: eth2
          peer_ip: 23.23.23.3/24
          peer_pod: r3
          uid: 3
  - apiVersion: networkop.co.uk/v1beta1
    kind: Topology
    metadata:
      name: r3
    spec:
      links:
        - local_intf: eth1
          local_ip: 13.13.13.3/24
          peer_intf: eth2
          peer_ip: 13.13.13.1/24
          peer_pod: r1
          uid: 2
        - local_intf: eth2
          local_ip: 23.23.23.3/24
          peer_intf: eth2
          peer_ip: 23.23.23.2/24
          peer_pod: r2
          uid: 3
  - apiVersion: v1
    kind: Pod
    metadata:
      labels:
        test: 3node
      name: r1
    spec:
      containers:
        - command:
            - /bin/sh
            - "-c"
            - sleep infinity
          image: alpine
          name: pod
  - apiVersion: v1
    kind: Pod
    metadata:
      labels:
        test: 3node
      name: r2
    spec:
      containers:
        - command:
            - /bin/sh
            - "-c"
            - sleep infinity
          image: alpine
          name: pod
  - apiVersion: v1
    kind: Pod
    metadata:
      labels:
        test: 3node
      name: r3
    spec:
      containers:
        - command:
            - /bin/sh
            - "-c"
            - sleep infinity
          image: alpine
          name: pod
kind: List
