---
apiVersion: batch/v1
kind: Job
metadata:
  generateName: flow-otg-otg-
  labels:
    flow: otg-otg
spec:
  backoffLimit: 1
  template:
    spec:
      containers:
        - command:
            - /bin/sh
            - "-c"
            - |
              curl -s -L https://raw.githubusercontent.com/raballew/kne-on-ocp/main/flows/flow-otg-otg.yaml > otg.yaml
              otgen run --file otg.yaml --api https://service-https-otg-controller --insecure --metrics flow | otgen transform --metrics flow --counters frames | otgen display --mode table
          image: ghcr.io/raballew/kne-on-ocp/otgen@sha256:7f21a7a527cd984b11728287c00862aa03d30bc627afbd6f979079bbf495a69b
          name: otgen
      restartPolicy: Never
