---
apiVersion: batch/v1
kind: Job
metadata:
  generateName: flow-r1-r3-
  labels:
    flow: r1-r2-r3
spec:
  backoffLimit: 1
  template:
    spec:
      containers:
        - command:
            - /bin/sh
            - "-c"
            - |
              curl -L https://raw.githubusercontent.com/raballew/kne-on-ocp/main/flows/flow-r1-r2-r3.yaml > otg.yaml
              otgen run --file otg.yaml --api https://service-https-otg-controller --insecure --metrics flow | otgen transform --metrics flow --counters frames | otgen display --mode table
          image: quay.io/pwallrab/otgen:0.1.0
          name: otgen
      restartPolicy: Never
