---
apiVersion: kustomize.config.k8s.io/v1beta1
commonLabels:
  app: meshnet
kind: Kustomization
patches:
  - patch: |-
      - op: add
        path: /rules/-
        value:
          apiGroups:
            - security.openshift.io
          resourceNames:
            - privileged
          resources:
            - securitycontextconstraints
          verbs:
            - use
    target:
      kind: ClusterRole
      name: meshnet-clusterrole
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/env/1
        value:
          name: INTER_NODE_LINK_TYPE
          value: VXLAN
    target:
      kind: DaemonSet
      name: meshnet
  - patch: |-
      - op: replace
        path: /spec/template/spec/volumes/0/hostPath
        value:
          path: /var/lib/cni/bin
    target:
      kind: DaemonSet
      name: meshnet
  - patch: |-
      - op: replace
        path: /spec/template/spec/volumes/1/hostPath
        value:
          path: /etc/kubernetes/cni/net.d
    target:
      kind: DaemonSet
      name: meshnet
resources:
  - ../../base/
