# Modified version of https://github.com/open-traffic-generator/ixia-c/releases/download/v0.0.1-3423/ixia-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: ixiatg-release-config
  namespace: ixiatg-op-system
data:
  versions: |
    {
      "release": "local-latest",
      "images": [
            {
                "name": "controller",
                "path": "registry.hub.docker.com/ixiacom/ixia-c-controller",
                "tag": "0.0.1-3423"
            },
            {
                "name": "gnmi-server",
                "path": "registry.hub.docker.com/ixiacom/ixia-c-gnmi-server",
                "tag": "1.9.5"
            },
            {
                "name": "traffic-engine",
                "path": "registry.hub.docker.com/ixiacom/ixia-c-traffic-engine",
                "tag": "1.6.0.19"
            }
        ]
    }
